/**
 * 用户认证相关常量
 */

// 认证方法
export const AUTH_METHODS = {
  EMAIL: 'email',
  PHONE: 'phone',
  GOOGLE: 'google',
  WECHAT: 'wechat',
  GITHUB: 'github'
} as const

// 用户类型
export const USER_TYPES = {
  FREE: 'FREE',
  PREMIUM: 'PREMIUM',
  PROFESSIONAL: 'PROFESSIONAL',
  ADMIN: 'ADMIN',
  BANNED: 'BANNED'
} as const

// 用户类型配额配置
export const USER_TYPE_QUOTAS = {
  FREE: { daily: 3, total: 100 },
  PREMIUM: { daily: 50, total: 1000 },
  PROFESSIONAL: { daily: 200, total: 5000 },
  ADMIN: { daily: -1, total: -1 }
}

// 验证码配置
export const VERIFICATION_CODE_CONFIG = {
  LENGTH: 6,
  EXPIRES_IN: 5 * 60, // 5分钟
  MAX_ATTEMPTS: 3,
  RESEND_COOLDOWN: 60, // 1分钟
  RATE_LIMIT: 10 // 每小时最多10次
}

// 密码策略
export const PASSWORD_POLICY = {
  MIN_LENGTH: 8,
  MAX_LENGTH: 128,
  REQUIRE_UPPERCASE: true,
  REQUIRE_LOWERCASE: true,
  REQUIRE_NUMBERS: true,
  REQUIRE_SYMBOLS: false,
  FORBIDDEN_PATTERNS: [
    'password',
    '123456',
    'qwerty',
    'admin'
  ]
}

// 社交登录配置
export const SOCIAL_PROVIDERS = {
  GOOGLE: {
    name: 'Google',
    clientId: import.meta.env.VITE_GOOGLE_CLIENT_ID,
    scopes: ['openid', 'profile', 'email']
  },
  WECHAT: {
    name: '微信',
    appId: import.meta.env.VITE_WECHAT_APP_ID,
    scopes: ['snsapi_userinfo']
  },
  GITHUB: {
    name: 'GitHub',
    clientId: import.meta.env.VITE_GITHUB_CLIENT_ID,
    scopes: ['user:email']
  }
}

// 错误码
export const AUTH_ERROR_CODES = {
  // 通用错误
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',

  // 认证错误
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DISABLED: 'USER_DISABLED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

  // 注册错误
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  TERMS_NOT_ACCEPTED: 'TERMS_NOT_ACCEPTED',

  // 验证错误
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  VERIFICATION_CODE_INVALID: 'VERIFICATION_CODE_INVALID',
  VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // 社交登录错误
  SOCIAL_AUTH_ERROR: 'SOCIAL_AUTH_ERROR',
  SOCIAL_AUTH_CANCELLED: 'SOCIAL_AUTH_CANCELLED',
  SOCIAL_ACCOUNT_ALREADY_LINKED: 'SOCIAL_ACCOUNT_ALREADY_LINKED',
  SOCIAL_EMAIL_ALREADY_EXISTS: 'SOCIAL_EMAIL_ALREADY_EXISTS'
} as const

// 错误消息
export const AUTH_ERROR_MESSAGES = {
  [AUTH_ERROR_CODES.UNKNOWN_ERROR]: '未知错误',
  [AUTH_ERROR_CODES.NETWORK_ERROR]: '网络连接错误',
  [AUTH_ERROR_CODES.SERVER_ERROR]: '服务器错误',
  [AUTH_ERROR_CODES.INVALID_CREDENTIALS]: '用户名或密码错误',
  [AUTH_ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [AUTH_ERROR_CODES.USER_DISABLED]: '账户已被禁用',
  [AUTH_ERROR_CODES.TOKEN_EXPIRED]: '登录已过期，请重新登录',
  [AUTH_ERROR_CODES.TOKEN_INVALID]: '无效的访问令牌',
  [AUTH_ERROR_CODES.REFRESH_TOKEN_INVALID]: '刷新令牌无效',
  [AUTH_ERROR_CODES.USER_ALREADY_EXISTS]: '用户已存在',
  [AUTH_ERROR_CODES.EMAIL_ALREADY_EXISTS]: '邮箱已被注册',
  [AUTH_ERROR_CODES.PHONE_ALREADY_EXISTS]: '手机号已被注册',
  [AUTH_ERROR_CODES.WEAK_PASSWORD]: '密码强度不够',
  [AUTH_ERROR_CODES.TERMS_NOT_ACCEPTED]: '请同意用户协议',
  [AUTH_ERROR_CODES.EMAIL_NOT_VERIFIED]: '邮箱未验证',
  [AUTH_ERROR_CODES.PHONE_NOT_VERIFIED]: '手机号未验证',
  [AUTH_ERROR_CODES.VERIFICATION_CODE_INVALID]: '验证码错误',
  [AUTH_ERROR_CODES.VERIFICATION_CODE_EXPIRED]: '验证码已过期',
  [AUTH_ERROR_CODES.TOO_MANY_ATTEMPTS]: '尝试次数过多，请稍后再试',
  [AUTH_ERROR_CODES.RATE_LIMIT_EXCEEDED]: '操作过于频繁，请稍后再试',
  [AUTH_ERROR_CODES.SOCIAL_AUTH_ERROR]: '社交登录失败',
  [AUTH_ERROR_CODES.SOCIAL_AUTH_CANCELLED]: '社交登录已取消',
  [AUTH_ERROR_CODES.SOCIAL_ACCOUNT_ALREADY_LINKED]: '该社交账号已绑定其他用户',
  [AUTH_ERROR_CODES.SOCIAL_EMAIL_ALREADY_EXISTS]: '该邮箱已被其他用户使用'
}
